### PR TITLE
adding parts of aggregated elements in output json

### PR DESCRIPTION
**Pull request by franky235**
in order to have coherent .jon and .wexbim files, added parts of aggregated elements (like roofs, stairs, curtainwalls,..) and corresponding spaces  in json output
tested with XbimWebUI on different models, all elements of models are now displayed by browser

### CODE REVIEW

**Comment by CBenghi** [comment]
@benjymous, 
Can you review this PR and merge if it makes sense?
Claudio

**Comment by CBenghi** [comment]
Perhaps @LaurenceSkoropinski could also have a look.
Claudio

**Comment by renyuanc7** [comment]
This fix really solved the problem.

Thanks @franky235 .

**Comment by theextremeandy** [comment]
This fix solved my problem too!
Tanks @franky235

**Pull request merged**
